# Generated by Django 5.2.7 on 2025-10-19 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_oper",
                    models.CharField(
                        help_text="Введите название типа операции", max_length=25
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(help_text="Сумма баланса кошелька")),
                (
                    "oper_type",
                    models.ForeignKey(
                        help_text="Тип операции",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallets.operationtype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Владелец",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
